name: state_tests
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Kristiyan <komapeb@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  pedantic: ^1.7.0
  equatable: ^0.2.6

dev_dependencies:
  test: ^1.0.0